name: Testing security scan - using sarif
on: [push]

jobs:
  build:
    name: sarif testing action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif/results.sarif
