version: "2"
services:
  goof:
    build: .
    container_name: goof
    environment:
      - DOCKER=1
    ports:
      - "3001:3001"
      - "9229:9229"
    links:
      - goof-mongo
    depends_on:
      - goof-mongo
  goof-mongo:
    container_name: goof-mongo
    image: mongo
    ports:
      - "27017:27017"
