name: "snyk code manual test"
on: [push, pull_request]

jobs:
  build:
    name: sarif testing action
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v2
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif.json
          # sarif_file: example111.json
